name: Clojure CI

on:
  push:
    branches: [ master, "feature/**", "refactor/**", "chore/**", "bugfix/**" ]
  pull_request:
    branches: [ master, "feature/**", "refactor/**", "chore/**", "bugfix/**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Compile
      run: lein compile
    - name: Build jar
      run: lein uberjar
    - name: Run tests
      run: lein test
